version: '3'
services:
  backend:
    stdin_open: true
    tty: true
    build: ./backend/
    ports:
      - "8000:8000"
    environment:
      open_ai_key: ${open_ai_key}
    networks:
      - webnet

  frontend:
    stdin_open: true
    tty: true
    build: ./frontend/
    ports:
      - "3000:3000"
    networks:
      - webnet

networks:
  webnet:
